name: Deploy Fullstack

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Frontend Build (Node.js)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies and build frontend
        run: |
          npm install
          npm run build

      - name: Package frontend
        run: tar -czvf frontend-build.tar.gz -C build .

      # Deploy Frontend (matching backend's structure)
      - name: Deploy Frontend
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "frontend-build.tar.gz"
          target: "/var/www/frontend/"
          strip_components: 0  # Keep directory structure intact

      # Post-Deploy Steps (aligned with backend)
      - name: Restart Services
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /var/www/frontend
            tar -xzvf frontend-build.tar.gz --strip-components=0  # Explicit extraction
            sudo systemctl restart nginx
